CREATE TABLE "service_requests" (
	"id" serial PRIMARY KEY NOT NULL,
	"reference_number" text NOT NULL,
	"client_type" text NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"phone" text NOT NULL,
	"company" text,
	"siret" text,
	"service_type" text NOT NULL,
	"request_type" text NOT NULL,
	"building_type" text NOT NULL,
	"project_status" text NOT NULL,
	"permit_number" text,
	"permit_delivery_date" text,
	"address" text NOT NULL,
	"address_complement" text,
	"city" text NOT NULL,
	"postal_code" text NOT NULL,
	"cadastral_reference" text,
	"power_required" text NOT NULL,
	"phase_type" text,
	"desired_completion_date" text,
	"billing_address" text,
	"billing_city" text,
	"billing_postal_code" text,
	"has_architect" boolean,
	"architect_name" text,
	"architect_phone" text,
	"architect_email" text,
	"comments" text,
	"estimated_price" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "service_requests_reference_number_unique" UNIQUE("reference_number")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
